# Generated by Django 5.2.7 on 2025-10-12 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='file_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('pdf', 'PDF'), ('doc', 'Document'), ('audio', 'Audio'), ('3d', '3D Model'), ('other', 'Other')], max_length=10),
        ),
    ]
